name: flutter_demos
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

  # 程序闪屏
  flutter_native_splash: ^0.3.0
  custom_splash: ^0.0.2

  #列表
  flutter_slidable: ^0.5.7
  flutter_staggered_animations: "^0.1.2"

  # 图片轮播
  flutter_swiper: ^1.1.6
  dot_pagination_swiper: ^0.1.1
  fule_swiper: ^0.1.2
  # 底部导航
  curved_navigation_bar: ^0.3.7
  ff_navigation_bar: ^0.1.4
  fancy_bottom_navigation: ^0.3.2
  bubbled_navigation_bar: ^0.0.3 #latest version
  navigation_action_bar: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  assets:
    - assets/images/icon/layout.png
    - assets/images/icon/list.png
    - assets/images/icon/bottom.png
    - assets/images/icon/jingdong.png
    - assets/images/icon/weixin.png
    - assets/images/icon/apple.png
    - assets/images/icon/setting.png
    - assets/images/icon/camera.png
    - assets/images/icon/swiper.png

    - assets/images/splash/splash.png

    - assets/images/layout/touxiang.png
    - assets/images/layout/pic1.png
    - assets/images/layout/pic2.png
    - assets/images/layout/pic3.png
    - assets/images/layout/pic4.png

    - assets/images/swiper/pic001.jpg
    - assets/images/swiper/pic002.jpg
    - assets/images/swiper/pic003.jpg

    - assets/images/home/jingdong/homeBg1.jpg
    - assets/images/home/jingdong/homeBg2.jpg
    - assets/images/home/jingdong/homeBg3.jpg
    - assets/images/home/jingdong/apple.png
    - assets/images/home/jingdong/camera.png
    - assets/images/home/jingdong/item1.png
    - assets/images/home/jingdong/sildbanner/pic001.jpg
    - assets/images/home/jingdong/sildbanner/pic002.jpg
    - assets/images/home/jingdong/sildbanner/pic003.jpg
    - assets/images/home/jingdong/sildbanner/pic004.jpg
    - assets/images/home/jingdong/sildbanner/pic005.jpg
    - assets/images/home/jingdong/sildbanner/pic006.jpg
    - assets/images/home/jingdong/sildbanner/pic007.jpg
    - assets/images/home/jingdong/sildbanner/pic008.jpg

    - assets/images//mine/weixin/touxiang.png
    - assets/images//mine/weixin/photo.png
    - assets/images//mine/weixin/emoji.png
    - assets/images//mine/weixin/favorite.png
    - assets/images//mine/weixin/pay.png
    - assets/images//mine/weixin/picture.png
    - assets/images//mine/weixin/card.png
    - assets/images//mine/weixin/setting.png
    - assets/images//mine/weixin/right.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
